### ISSUE TITLE
Segui as instruções e estava dando uma NullPointerException

### ISSUE THREAD

**Issue by cleuton** [demoiselle/generator-demoiselle#1]
jboss Caused by: java.lang.NullPointerException     at org.hibernate.annotations.CacheConcurrencyStrategy.fromAccessType(CacheConcurrencyStrategy.java:52)

Eu segui esse post do StackOverflow: http://stackoverflow.com/questions/7738495/eclipselink-to-hibernate-migration

E mexi no persistence.xml: 

```
    <!-- <shared-cache-mode>ALL</shared-cache-mode> -->
    <properties>
```

<property name="hibernate.cache.use_second_level_cache"
                value="true" />

**Comment by PauloGladson** [comment]
Obrigado, vou fazer a correção!

**Comment by mbacefor** [comment]
Também fiz esta mudança e funcionou .

**Comment by PauloGladson** [comment]
Estará implementado na próxima versão, obrigado pela colaboração 


Obter o Outlook para Android






On Sun, Jul 10, 2016 at 4:31 PM -0300, "Marcelo" <notifications@github.com> wrote:












Também fiz esta mudança e funcionou .
