### ISSUE TITLE
Problema na injeção do bc de user 

### ISSUE THREAD

**Issue by mbacefor** [demoiselle/generator-demoiselle#4]
Não estou conseguindo visualizar a grid de usuário, pois o userbc não é injetado. Estoh usando java7 e jboss7.

**Comment by PauloGladson** [comment]
Os BC já está na classe AbstractREST e você pode injetar um novo bc na classe rest, o bc herdado vai ter acesso aos métodos padrões já existentes e via cast aos novos métodos, vou preparar um novo vídeo e publicar um exemplo disso.
